max_train_samples: 512
max_val_samples: 2048
summary_—Åompression: 20
per_device_train_batch_size: [1, 1, 1, 2, 2, 3, 4]
per_device_eval_batch_size: [8, 10, 10, 10, 16, 16, 16]
segments_per_substep: [1, 1, 2, 2, 4, 3, 3]
training_substeps: [1, 4, 3, 4, 4, 8, 16]